# Generated by Django 6.0 on 2025-12-27 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='has_received_signup_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='token_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='total_earned',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='wallet_type',
            field=models.CharField(default='ethereum', max_length=20),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('token_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('referrer_bonus', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('user_bonus', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='referral.walletuser')),
            ],
        ),
        migrations.CreateModel(
            name='TokenReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('reward_type', models.CharField(choices=[('signup_referral', 'پاداش ثبت\u200cنام زیرمجموعه'), ('purchase_self', 'پاداش خرید خود کاربر'), ('purchase_referral', 'پاداش خرید زیرمجموعه')], max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referral.purchase')),
                ('related_referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referral.referral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_rewards', to='referral.walletuser')),
            ],
        ),
    ]
