# Generated by Django 6.0 on 2025-12-27 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_referral_has_received_signup_bonus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenreward',
            name='related_purchase',
        ),
        migrations.AddField(
            model_name='walletuser',
            name='total_staked',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tokenreward',
            name='reward_type',
            field=models.CharField(choices=[('signup_referral', 'پاداش ثبت\u200cنام زیرمجموعه'), ('staking_self', 'پاداش استیکینگ خود کاربر'), ('staking_referral', 'پاداش استیکینگ زیرمجموعه'), ('staking_unlock', 'برداشت از استیکینگ')], max_length=50),
        ),
        migrations.CreateModel(
            name='Staking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bonus_received', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('referrer_bonus', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('staked_at', models.DateTimeField(auto_now_add=True)),
                ('unlock_date', models.DateTimeField()),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakings', to='referral.walletuser')),
            ],
            options={
                'ordering': ['-staked_at'],
            },
        ),
        migrations.AddField(
            model_name='tokenreward',
            name='related_staking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referral.staking'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
